/**
 * Copyright (c) 2026 Ada Technology. MIT License.
 */
import './cargo-volume/cargo-volume.contract'
import './cargo-volume/tenant-safety.contract'
import './fleet-domain/vehicle-capacity.contract'
import './cargo-volume/trip-occupancy.contract'
import './cargo-volume/measured-cargo-volume.contract'
import './cargo-volume/weight-concentration.contract'
import './cargo-volume/cargo-layout.contract'
import './cargo-volume/cargo-layout-rows.contract'
import './cargo-volume/cargo-depth.contract'
import './cargo-volume/cargo-plan.contract'
import './cargo-volume/cargo-preview.contract'
import './cargo-weight/document-cargo-weight.contract'
import './cargo-weight/trip-cargo-weight.contract'
import './cargo-placement/arrangement.contract.js'
import './cargo-placement/grid.contract.js'
import './cargo-placement/delivery-block.contract.js'
import './cargo-placement/placement.contract.js'
import './cargo-placement/slices.contract.js'
import './cargo-placement/real-mixed-cargo.contract.js'
import './cargo-placement/side-gap-brace.contract.js'
import './cargo-placement/dead-space.contract.js'
import './cargo-placement/unloading.contract.js'
import './cargo-placement/note-identity.contract.js'
import './cargo-placement/complement.contract.js'
