/**
 * Copyright (c) 2026 Ada Technology. MIT License.
 */
import './database-migration/static-migration.contract.js'
import './database-migration/cargo-arrival-receiving-occurrence-migration.contract.js'
import './database-migration/occurrence-type-requirement-modes.static.contract.js'
import './database-migration/occurrence-type-quantity-minimums.static.contract.js'
import './database-migration/occurrence-type-moments.static.contract.js'
import './database-migration/occurrence-declared-amount.static.contract.js'
import './database-migration/nfe-recipient-email.static.contract.js'
import './database-migration/occurrence-type-icon.static.contract.js'
import './database-migration/cargo-preview-retention.static.contract.js'
import './database-migration/nfe-recipient-email-backfill-job.static.contract.js'
import './database-migration/business-calendar.static.contract.js'
import './database-migration/holiday-provider-import.static.contract.js'
import './database-migration/holiday-provider-settings.static.contract.js'
import './database-migration/nfe-addresses-participant-index.static.contract.js'
import './database-migration/conversation-protocol.static.contract.js'
import './database-migration/conversation-subject.static.contract.js'
import './database-migration/street-occurrence-attachment-backfill.static.contract.js'
import './database-migration/schema-snapshot.contract.js'
import './database-migration/migration-readiness.contract.js'
import './database-migration/pre-deploy.contract.js'
import './database-migration/stored-object-bucket-repair.contract.js'
import './database-migration/database-migration.integration.js'
import './database-migration/trip-backfill.integration.js'
