/**
 * Copyright (c) 2026 Ada Technology. MIT License.
 */
import './trip-http/create.contract.js'
import './trip-http/documents.contract.js'
import './trip-http/close.contract.js'
import './trip-http/crew.contract.js'
import './trip-http/location-tracking.contract.js'
import './trip-http/mdfe-manifest.contract.js'
import './trip-http/mdfe-requirement.contract.js'
import './trip-http/valuation.contract.js'
import './trip-http/costs.contract.js'
import './trip-http/list.contract.js'
import './trip-http/detail.contract.js'
import './trip-http/cargo-layout.contract.js'
import './trip-http/security.contract.js'
import './trip-http/money-redaction.contract.js'
import './trip-http/list-money-redaction.contract.js'
import './trip-http/driver-redaction.contract.js'
import './trip-http/allowed-actions.contract.js'
import './trip-http/timeline.contract.js'
import './trip-http/occurrence-case.contract.js'
import './trip-http/occurrence-detail.contract.js'
import './trip-http/occurrence-settlement.contract.js'
import './trip-http/redelivery-proposal.contract.js'
