/**
 * Copyright (c) 2026 Ada Technology. MIT License.
 */
import './trip-occurrence/attachment-errors.contract'
import './trip-occurrence/attachment-pdf.contract'
import './trip-occurrence/attachment-policy.contract'
import './trip-occurrence/attachment-read.contract'
import './trip-occurrence/attachment-required.contract'
import './trip-occurrence/catalog.contract'
import './trip-occurrence/register.contract'
import './trip-occurrence/notification.contract'
import './trip-occurrence/stop-notification.contract'
import './trip-occurrence/settings.contract'
import './trip-occurrence/driver.contract'
import './trip-occurrence/item-quantity.contract'
import './trip-occurrence/item-quantity-registration.contract'
import './trip-occurrence/item-quantity-schema.contract'
import './trip-occurrence/product-codes.contract'
import './trip-occurrence/product-selection.contract'
import './trip-occurrence/scope.contract'
import './trip-occurrence/template.contract'
import './trip-occurrence/template-key.contract'
import './trip-occurrence/feed.contract'
import './trip-occurrence/detail.contract'
import './trip-occurrence/timeline.contract'
import './trip-occurrence/catalog-seed.contract'
import './trip-occurrence/separation-upload.contract'
import './trip-occurrence/attachment-append.contract'
import './trip-occurrence/attachment-mode-schema.contract'
import './trip-occurrence/upload.contract'
import './trip-occurrence/leaves-document-behind-schema.contract'
import './trip-occurrence/leaves-document-behind.contract'
