/**
 * Copyright (c) 2026 Ada Technology. MIT License.
 */
import './whatsapp-commands/whatsapp-phone.contract.js'
import './whatsapp-commands/resolve-whatsapp-actor.contract.js'
import './whatsapp-commands/command-driver.contract.js'
import './whatsapp-commands/authorized-actor.contract.js'
import './whatsapp-commands/phone-verification.contract.js'
import './whatsapp-commands/phone-verification-routes.contract.js'
import './whatsapp-commands/whatsapp-menu-policy.contract.js'
import './whatsapp-commands/dynamic-choice.contract.js'
import './whatsapp-commands/membership-policy-lock.contract.js'
import './whatsapp-commands/root-menu-permission.contract.js'
import './whatsapp-commands/flow-graph-diff.contract.js'
import './whatsapp-commands/flow-graph.contract.js'
import './whatsapp-commands/publish-flow-graph.contract.js'
import './whatsapp-commands/driver-flow-actions.contract.js'
import './whatsapp-commands/operator-flow-actions.contract.js'
import './whatsapp-commands/preview-digest.contract.js'
import './whatsapp-commands/document-selection-policy.contract.js'
import './whatsapp-commands/issuance-volumetry.contract.js'
import './whatsapp-commands/document-selection-tenant-safety.contract.js'
import './whatsapp-commands/preview-document-selection.contract.js'
import './whatsapp-commands/issuance-flow-actions.contract.js'
import './whatsapp-commands/confirm-document-selection.contract.js'
import './whatsapp-commands/whatsapp-command-settlement-policy.contract.js'
import './whatsapp-commands/settle-whatsapp-command.contract.js'
import './whatsapp-commands/settlement-routes.contract.js'
import './whatsapp-commands/incoming-image-context.contract.js'
