/**
 * Copyright (c) 2026 Ada Technology. MIT License.
 *
 * Spec 238 T1.3: as recusas do cadastro do calendário, cada uma com código estável. Editar o que não
 * existe é 404; apagar o que não existe é no-op e não passa por aqui.
 */
import { ApiError } from '../../shared/api.error.js'
import { DiagnosableError } from '../../shared/diagnosable.error.js'
import { BUSINESS_CALENDAR_RULE_ERROR_CODE } from './business-calendar.constant.js'

const CODE = BUSINESS_CALENDAR_RULE_ERROR_CODE

export class MunicipalHolidayRuleNotFoundError extends ApiError {
  public constructor() {
    super({
      code: CODE.MUNICIPAL_HOLIDAY_RULE_NOT_FOUND,
      message: 'Municipal holiday rule was not found',
      status: 404,
    })
  }
}

/** Mesma cidade e mesmo dia com nome ou tipo diferente: a regra existente decide, não a nova. */
export class MunicipalHolidayRuleConflictError extends ApiError {
  public constructor() {
    super({
      code: CODE.MUNICIPAL_HOLIDAY_RULE_CONFLICT,
      message: 'A rule for this city and day already exists with a different name or kind',
      status: 409,
    })
  }
}

/** Na edição o mês e o dia se conferem juntos: `31` com `abril` só aparece depois de mesclar. */
export class MunicipalHolidayRuleInvalidDayError extends ApiError {
  public constructor() {
    super({
      code: CODE.MUNICIPAL_HOLIDAY_RULE_INVALID_DAY,
      details: [{ field: 'day', message: 'The day does not exist in the month' }],
      message: 'The day does not exist in the month',
      status: 400,
    })
  }
}

export class MunicipalHolidayNotFoundError extends ApiError {
  public constructor() {
    super({
      code: CODE.MUNICIPAL_HOLIDAY_NOT_FOUND,
      message: 'Municipal holiday was not found',
      status: 404,
    })
  }
}

/** A data gerada é da regra: editar ou apagar a regra é o caminho, não mexer na linha. */
export class MunicipalHolidayGeneratedByRuleError extends ApiError {
  public constructor() {
    super({
      code: CODE.MUNICIPAL_HOLIDAY_GENERATED_BY_RULE,
      message: 'This date was generated by a yearly rule: edit or delete the rule instead',
      status: 409,
    })
  }
}

export class StateHolidayNotFoundError extends ApiError {
  public constructor() {
    super({
      code: CODE.STATE_HOLIDAY_NOT_FOUND,
      message: 'State holiday was not found',
      status: 404,
    })
  }
}

export class StateHolidayConflictError extends ApiError {
  public constructor() {
    super({
      code: CODE.STATE_HOLIDAY_CONFLICT,
      message: 'A state holiday already exists for this state and date',
      status: 409,
    })
  }
}

/** `once` e `yearly` têm campos diferentes: o corpo do `PATCH` tem de ser da forma do feriado. */
export class StateHolidayRecurrenceMismatchError extends ApiError {
  public constructor() {
    super({
      code: CODE.STATE_HOLIDAY_RECURRENCE_MISMATCH,
      details: [{ field: 'recurrence', message: 'Does not match the stored holiday' }],
      message: 'The recurrence does not match the stored holiday',
      status: 400,
    })
  }
}

/** Desligar só vale de hoje em diante (D7): apagar a data passada mudaria o selo de prazo da nota já entregue. */
export class ImportedHolidayInThePastError extends ApiError {
  public constructor() {
    super({
      code: CODE.HOLIDAY_IMPORT_PAST_DATE,
      message: 'An imported holiday can only be disabled from today onwards',
      status: 409,
    })
  }
}

/** A digitada e a gerada por regra não têm o que desligar: o caminho delas é o `DELETE` do feriado. */
export class HolidayNotImportedError extends ApiError {
  public constructor() {
    super({
      code: CODE.HOLIDAY_NOT_IMPORTED,
      message: 'This holiday was not imported: delete it instead',
      status: 409,
    })
  }
}

/** A mensagem é fixa, então pode ir para o log sem carregar dado da empresa. */
export class BusinessCalendarPersistenceError extends DiagnosableError {
  public override readonly name = 'BusinessCalendarPersistenceError'

  public constructor() {
    super('A business calendar row could not be persisted')
  }
}
