/* Copyright (c) 2026 Ada Technology. MIT License. */
import { CANHOTO_REVIEW_NOTE_ERROR } from './canhotoReviewNote.validation'

export const CANHOTO_REJECT_NOTE_REASON = 'other'

export const CANHOTO_REJECT_ERROR_KEY = {
  LENGTH_RANGE: 'lengthRange',
  NOT_ALLOWED: 'notAllowed',
  PERSONAL_DATA: 'personalData',
  REQUEST_FAILED: 'requestFailed',
  REQUIRED: 'required',
  TOO_LONG: 'tooLong',
  TOO_SHORT: 'tooShort',
} as const
export type CanhotoRejectErrorKey =
  (typeof CANHOTO_REJECT_ERROR_KEY)[keyof typeof CANHOTO_REJECT_ERROR_KEY]

export const CANHOTO_REJECT_CLIENT_ERROR_KEY = {
  [CANHOTO_REVIEW_NOTE_ERROR.PERSONAL_DATA]: CANHOTO_REJECT_ERROR_KEY.PERSONAL_DATA,
  [CANHOTO_REVIEW_NOTE_ERROR.TOO_LONG]: CANHOTO_REJECT_ERROR_KEY.TOO_LONG,
  [CANHOTO_REVIEW_NOTE_ERROR.TOO_SHORT]: CANHOTO_REJECT_ERROR_KEY.TOO_SHORT,
} as const

export const CANHOTO_REJECT_SERVER_ERROR_KEY: Readonly<Record<string, CanhotoRejectErrorKey>> = {
  CANHOTO_REVIEW_NOTE_LENGTH: CANHOTO_REJECT_ERROR_KEY.LENGTH_RANGE,
  CANHOTO_REVIEW_NOTE_NOT_ALLOWED: CANHOTO_REJECT_ERROR_KEY.NOT_ALLOWED,
  CANHOTO_REVIEW_NOTE_PERSONAL_DATA: CANHOTO_REJECT_ERROR_KEY.PERSONAL_DATA,
  CANHOTO_REVIEW_NOTE_REQUIRED: CANHOTO_REJECT_ERROR_KEY.REQUIRED,
}
