CREATE TABLE "toll_booth_extracts" (
	"dataset" varchar(64),
	"observed_on" date,
	"object_key" text NOT NULL,
	"sha256" text NOT NULL,
	"booth_count" integer NOT NULL,
	"booths_with_charge" integer NOT NULL,
	"booths_with_axle_charge" integer NOT NULL,
	"source_url" text,
	"extracted_at" timestamp with time zone,
	"uploaded_by_user_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"missing_object_observed_at" timestamp with time zone,
	"reloaded_at" timestamp with time zone,
	"reloaded_by_user_id" uuid,
	"reloaded_booth_count" integer,
	CONSTRAINT "toll_booth_extracts_pkey" PRIMARY KEY("dataset","observed_on"),
	CONSTRAINT "toll_booth_extracts_dataset_check" CHECK ("dataset" ~ '^[a-z0-9][a-z0-9-]*$'),
	CONSTRAINT "toll_booth_extracts_object_key_check" CHECK ("object_key" ~ '^toll-booths/osm/[a-z0-9-]+/[0-9]{4}-[0-9]{2}-[0-9]{2}/toll-booths\.json$'),
	CONSTRAINT "toll_booth_extracts_sha256_check" CHECK ("sha256" ~ '^[0-9a-f]{64}$'),
	CONSTRAINT "toll_booth_extracts_counts_check" CHECK ("booth_count" > 0 and "booths_with_charge" between 0 and "booth_count" and "booths_with_axle_charge" between 0 and "booths_with_charge"),
	CONSTRAINT "toll_booth_extracts_source_url_check" CHECK ("source_url" is null or "source_url" ~ '^https://'),
	CONSTRAINT "toll_booth_extracts_reload_check" CHECK (("reloaded_at" is null) = ("reloaded_by_user_id" is null) and ("reloaded_at" is null) = ("reloaded_booth_count" is null) and ("reloaded_booth_count" is null or "reloaded_booth_count" >= 0)),
	CONSTRAINT "toll_booth_extracts_timeline_check" CHECK (("reloaded_at" is null or "reloaded_at" >= "created_at") and ("missing_object_observed_at" is null or "missing_object_observed_at" >= "created_at"))
);
