/* Copyright (c) 2026 Ada Technology. MIT License. */
import './cargo-receiving/separation-touch.contract'
import './cargo-receiving/document-selection.contract'
import './cargo-receiving/idempotency-key.contract'
import './cargo-receiving/arrival-form.contract'
import './cargo-receiving/refusal.contract'
import './cargo-receiving/response-validation.contract'
import './cargo-receiving/client.contract'
import './cargo-receiving/arrival-table.contract'
import './cargo-receiving/arrival-groups.contract'
import './cargo-receiving/route-and-access.contract'
import './cargo-receiving/preview-upload.contract'
import './cargo-receiving/preview-client.contract'
import './cargo-receiving/preview-response-validation.contract'
import './cargo-receiving/preview-table.contract'
import './cargo-receiving/preview-detail-view.contract'
import './cargo-receiving/preview-proposal-and-routes.contract'
import './cargo-receiving/preview-refusal.contract'
