/* Copyright (c) 2026 Ada Technology. MIT License. */
import './delivery-clients/window-editor.contract'
import './delivery-clients/contractor-mail-checklist.contract'
import './delivery-clients/contractor-mail-form.contract'
import './delivery-clients/contractor-mail-response.contract'
import './delivery-clients/contractor-contacts-validation.contract'
import './delivery-clients/contractor-contacts-response.contract'
import './delivery-clients/contractor-mail-templates-validation.contract'
import './delivery-clients/contractor-mail-templates-variable-insertion.contract'
import './delivery-clients/contractor-mail-templates-response.contract'
import './delivery-clients/contractor-mail-templates-errors.contract'
import './delivery-clients/contractor-mail-templates-client.contract'
