/* Copyright (c) 2026 Ada Technology. MIT License. */
import './fleet/client-and-queries.contract.js'
import './fleet/driver-vehicles.contract.js'
import './fleet/permissions-and-states.contract.js'
import './fleet/plate-lookup-removed.contract.js'
import './fleet/plate-thumbnail.contract.js'
import './fleet/presentation-boundaries.contract.js'
import './fleet/screen-standards.contract.js'
import './fleet/vehicle-columns.contract.js'
import './fleet/vehicle-completeness.contract.js'
import './fleet/vehicle-cost-fields.contract.js'
import './fleet/vehicle-model-fields.contract.js'
import './fleet/workspace-tabs.contract.js'
