ALTER TABLE "company_fiscal_profiles" DROP CONSTRAINT "company_fiscal_profiles_cnpj_check", ADD CONSTRAINT "company_fiscal_profiles_cnpj_check" CHECK ("cnpj" ~ '^[A-Z0-9]{12}[0-9]{2}$');--> statement-breakpoint
ALTER TABLE "company_fiscal_profiles" DROP CONSTRAINT "company_fiscal_profiles_mdfe_insurer_tax_id_check", ADD CONSTRAINT "company_fiscal_profiles_mdfe_insurer_tax_id_check" CHECK (length("mdfe_insurer_tax_id") = 0 or "mdfe_insurer_tax_id" ~ '^[0-9]{11}$|^[A-Z0-9]{12}[0-9]{2}$');--> statement-breakpoint
ALTER TABLE "digital_certificates" DROP CONSTRAINT "digital_certificates_validated_cnpj_check", ADD CONSTRAINT "digital_certificates_validated_cnpj_check" CHECK ("validated_cnpj" ~ '^[A-Z0-9]{12}[0-9]{2}$');--> statement-breakpoint
ALTER TABLE "nfe_documents" DROP CONSTRAINT "nfe_documents_access_key_check", ADD CONSTRAINT "nfe_documents_access_key_check" CHECK ("access_key" ~ '^[0-9]{6}[A-Z0-9]{12}[0-9]{26}$');--> statement-breakpoint
ALTER TABLE "nfe_events" DROP CONSTRAINT "nfe_events_access_key_check", ADD CONSTRAINT "nfe_events_access_key_check" CHECK ("target_access_key" ~ '^[0-9]{6}[A-Z0-9]{12}[0-9]{26}$');--> statement-breakpoint
ALTER TABLE "nfe_import_items" DROP CONSTRAINT "nfe_import_items_access_key_check", ADD CONSTRAINT "nfe_import_items_access_key_check" CHECK ("access_key" is null or "access_key" ~ '^[0-9]{6}[A-Z0-9]{12}[0-9]{26}$');--> statement-breakpoint
ALTER TABLE "cte_fiscal_documents" DROP CONSTRAINT "cte_fiscal_documents_access_key_check", ADD CONSTRAINT "cte_fiscal_documents_access_key_check" CHECK ("access_key" ~ '^[0-9]{6}[A-Z0-9]{12}[0-9]{26}$');--> statement-breakpoint
ALTER TABLE "billing_invoice_items" DROP CONSTRAINT "billing_invoice_items_cte_access_key_check", ADD CONSTRAINT "billing_invoice_items_cte_access_key_check" CHECK ("cte_access_key" ~ '^[0-9]{6}[A-Z0-9]{12}[0-9]{26}$');--> statement-breakpoint
ALTER TABLE "billing_invoices" DROP CONSTRAINT "billing_invoices_customer_document_check", ADD CONSTRAINT "billing_invoices_customer_document_check" CHECK ("customer_document" ~ '^[0-9]{11,14}$|^[A-Z0-9]{12}[0-9]{2}$');--> statement-breakpoint
ALTER TABLE "fleet_drivers" DROP CONSTRAINT "fleet_drivers_linked_tax_id_check", ADD CONSTRAINT "fleet_drivers_linked_tax_id_check" CHECK (length("linked_tax_id") = 0 or "linked_tax_id" ~ '^[A-Z0-9]{12}[0-9]{2}$');--> statement-breakpoint
ALTER TABLE "fleet_vehicles" DROP CONSTRAINT "fleet_vehicles_owner_tax_id_check", ADD CONSTRAINT "fleet_vehicles_owner_tax_id_check" CHECK (length("owner_tax_id") = 0 or "owner_tax_id" ~ '^[0-9]{11}$' or "owner_tax_id" ~ '^[A-Z0-9]{12}[0-9]{2}$');--> statement-breakpoint
ALTER TABLE "mdfe_fiscal_documents" DROP CONSTRAINT "mdfe_fiscal_documents_access_key_check", ADD CONSTRAINT "mdfe_fiscal_documents_access_key_check" CHECK ("access_key" ~ '^[0-9]{6}[A-Z0-9]{12}[0-9]{26}$');--> statement-breakpoint
ALTER TABLE "mdfe_manifest_items" DROP CONSTRAINT "mdfe_manifest_items_access_key_check", ADD CONSTRAINT "mdfe_manifest_items_access_key_check" CHECK ("access_key" ~ '^[0-9]{6}[A-Z0-9]{12}[0-9]{26}$');--> statement-breakpoint
ALTER TABLE "mdfe_manifests" DROP CONSTRAINT "mdfe_manifests_contractor_tax_id_check", ADD CONSTRAINT "mdfe_manifests_contractor_tax_id_check" CHECK (length("contractor_tax_id") = 0 or "contractor_tax_id" ~ '^[0-9]{11}$|^[A-Z0-9]{12}[0-9]{2}$');--> statement-breakpoint
ALTER TABLE "nfse_provider_credentials" DROP CONSTRAINT "nfse_provider_credentials_tax_id_check", ADD CONSTRAINT "nfse_provider_credentials_tax_id_check" CHECK ("tax_id" ~ '^[A-Z0-9]{12}[0-9]{2}$');--> statement-breakpoint
ALTER TABLE "nfse_service_invoices" DROP CONSTRAINT "nfse_service_invoices_taker_tax_id_check", ADD CONSTRAINT "nfse_service_invoices_taker_tax_id_check" CHECK ("taker_tax_id" ~ '^[0-9]{11}$|^[A-Z0-9]{12}[0-9]{2}$');--> statement-breakpoint
ALTER TABLE "cte_emission_profile_matchers" DROP CONSTRAINT "cte_emission_profile_matchers_tax_id_check", ADD CONSTRAINT "cte_emission_profile_matchers_tax_id_check" CHECK ("tax_id" ~ '^[A-Z0-9]{8}$' or "tax_id" ~ '^[A-Z0-9]{12}[0-9]{2}$');